### PR TITLE
Feature: Newtonsoft.Json support

### PR DESCRIPTION
**Pull request by yellowisher**
Love the idea, but some projects (including mine!) are already using `Newtonsoft.Json`.
So I added `UnitGenerateOptions.NewtonsoftJsonConvert`.

I had to fully query namespace for Json things to avoid name conflicts.
It might be OK to ignore such conflicts, though. (because using `JsonConvert | NewtonsoftJsonConvert` doesn't make sense)

### CODE REVIEW

**Comment by slimshader** [comment]
will this ever be merged?

**Comment by neuecc** [comment]
Sorry, I am not interested in supporting Newtonsoft.

**Comment by slimshader** [comment]
I see. May I ask why tho? I know it is not the coolest one on the block anymore but it is still the most used one by far (not always easy to just replace to new one)

**Comment by neuecc** [comment]
Well, it might still be widely used, but I never really liked that library to begin with.
And since UnitGenerator is a new library, I don't want to support it.

**Pull request closed without merging**
